version: "3.3"
services:
  label_studio:
    image: heartexlabs/label-studio:latest
    container_name: label_studio
    restart: unless-stopped
    ports:
      - 80:8080
    env_file:
      - .env
    volumes:
      - ${LABEL_STUDIO_DIRECTORY}:/label-studio/data

volumes:
  label-studio-data-volumen:
